LVBM_PN = {
	["en"] = {
		[200] = {
			[1]			= "v2.00",
			[2]			= " ",
			[3]			= "*** delete your old La_Vendetta_Boss_Mods and restart WoW after installing v2.00 ***",
			[4]			= "all boss mods are now load on demand addons",
			[5]			= "updated Four Horsemen boss mod",
			[6]			= "updated Sapphiron mod",
			[7]			= "updated Hakkar boss mod (pull detection)",
			[8]			= "updated Nefarian boss mod (kill counter)",
			[9]			= "updated zhTW translations (thanks to CuteMiyu, hmj1026)",
			[10]		= "updated zhCN translations (thanks to DiabloHu)",
			[11]		= "updated frFR translations (thanks to cr0k and Proreborn)",
			[12]		= "updated deDE translations",
			[13]		= "added more options to some boss mods",
			[14]		= " ",
			[15]		= "fixed Battleground statusbar color bug",
			[16]		= "fixed Gui bug with disabled sync",
			[17]		= "fixed Patchwork boss mod error message",
			[18]		= "fixed API bug on filtering outdated client syncs",
			[19]		= "fixed debugstack bug",
			[20]		= "fixed some localization bugs",
			[21]		= "fixed many minor bugs",
			[22]		= "fixed range check frame toggle function bug",
			[23]		= "fixed a positioning bug in the InfoFrame code",
			[24]		= " ",
			[25]		= "added LV_RaidTools v0.3",
			[26]		= "added LVRT slash command \"/lvrt\" with help messages",
			[27]		= "added LVRT slash command \"/lvrt ver\"",
			[28]		= "added LVRT slash command \"/lvrt emote <emote> [target]\"",
			[29]		= "added LVRT slash command \"/lvrt enable <AddOn> <Player>\"",
			[30]		= "added LVRT slash command \"/lvrt disable <AddOn> <Player>\"",
			[31]		= "added LVRT slash command \"/lvrt announce <AddOn> <Player> <on|off>\"",
			[32]		= "added LVRT slash command \"/lvrt bosslist\"",
			[33]		= "added LVRT slash command \"/lvrt remote <option> <on|off>\"",
			[34]		= "added LVRT slash command \"/lvrt logout <name>\" (needs promoted or leader)",
			[35]		= "added LVRT slash command \"/lvrt pull <x>\"",
			[36]		= "added LVRT slash command \"/lvrt ui\" to reload you UI",
			[37]		= "moved slash command \"/pull <x>\" to LVRT",
			[38]		= "added new boss translation system for statusbars with dynamic content (LVBM_SBT[addon][x]={\"search\", \"replace\"})",
			[39]		= "added GUI option to change the combat log range",
			[40]		= "added Thaddius lag fix by reducing the combat log range during phase 2",
			[41]		= "added Four Horsemen InfoFrame to see the current boss hitpoints",
			[42]		= "added new sync filter system for bars (filters out wrong/old AB and 4H Bars)",
			[43]		= " ",
			[44]		= "removed some old debug code",
			[45]		= "separated API, GUI, BossMods and RaidTools for performance tweaks",
			[46]		= "optimized loading times",
			[47]		= "optimized memory usage",
		},
		[192] = {
			[1]			= "v1.92",
			[2]			= "fixed some bar problems",
			[3]			= "fixed Four Horsemen AddOn (Mark problem with Bars)",
			[4]			= "fixed Grand Widow Faerlina out of Range Problem (now sync Enrage)",
			[5]			= "fixed some missing Localization Strings",
			[6]			= "fixed GUI first time scroll bug",
			[7]			= "",
			[8]			= "updated Grand Widow Faerlina for deDE Client (enrage Detection timers)",
			[9]			= "updated Four Horsemen AddOn Meteor Code",
			[11]			= "updated AQ20 Anubisath Mod",
			[10]			= "updated Localizations",
			[11]			= "",
			[12]			= "added Gui Option to disable Sync with old Clients",
			[13]			= "added Gui Option to Hide Playernames in Raidgroups",
			[14]			= "added API Option in BossTemplate to handle old Version Syncs",
			[15]			= "added Slashcommand \"/lv ver2\" which informs users with outdated versions",
			[16]			= "added Slashcommand \"/pull <x>\" (x = sec)";
		},
		[191] = {
			[1]			= "v1.91",
			[2]			= "creating new bars no longer sets the status bars color to default",
			[3]			= "fixed some minor bugs in the combat detection system",
			[4]			= "fixed a bug in the Loatheb healer rotation sync system with /loatheb undelete",
			[5]			= "fixed Sapphiron emote, Blizzard forgot %s in their emote string",
			[6]			= "fixed Kel'Thuzad combat detection bug",
			[7]			= "",
			[8]			= "optimized status bar code -> reduced bar memory usage by ~30%, fixed memory leak bug in PullBarsTogether function",
			[9]			= "optimized Loatheb sync code -> reduced channel spam",
			[10]			= "players without (A) or (L) can now set a healer rotation for Loatheb, but their settings can't be broadcasted",
			[11]			= "you can now disable the \"status\" whisper command",
			[12]			= "changed default bar design",
			[13]			= "improved Sapphiron mod",
			[14]			= "improved Kel'Thuzad mod",
			[15]			= "updated BG mod, it now uses colored bars",
			[16]			= "updated chinese localization (thanks 2 DiabloHu)",
			[17]			= "",
			[18]			= "added support for Lua 5.1 (Burning Crusade)",
			[19]			= "status bars will now flash when they are about to expire",
			[20]			= "status bars will now change their color over time",
			[21]			= "added french translation (only GUI and Blackwing Lair, more coming soon) (thanks 2 Proreborn)",
		},
	},
	["de"] = {
		[190] = {
			[1]			= "v1.90",
			[2]			= "Buru %s Bug gefixt",
			[3]			= "Huhuran %s Frenzy Bug gefixt",
			[4]			= "Moam Steinform Erkennung gefixt",
			[5]			= "Ossirians Fluch gefixt",
			[6]			= "Battleground 5vs0 Timer gefixt",
			[7]			= "InfoFrame Positionierungsbug gefixt",
			[8]			= "InfoFrame:Delete() gefixt, Script Handler werden nun korrekt entfernt",
			[9]			= "einige kleinere Fehler im InfoFrame behoben",
			[10]		= "Kompatibilitätsprobleme mit Chat AddOns behoben, whisper werden nun korrekt ausgeblendet",
			[11]		= "der Yauj Fear Timer kann nicht mehr von anderen Mobs in AQ40 gestartet werden",
			[12]		= "einige Probleme mit der Synchronisation wurden behoben",
			[13]		= " ",
			[14]		= "InfoFrames speichern nun ihre Position",
			[15]		= "Pizzatimer zeigen nun 10 Sekunden bevor sie auslaufen eine Warnung an",
			[16]		= "Anub'Rekhan Timer leicht angepasst, Nachrichten für den ersten Heuschreckenschwarm geändert",
			[17]		= "Gluths Dezimieren Timer angepasst",
			[18]		= "Razuvious Timers so verändert, dass sie nun \"Repeating Bars\" verwenden, das wird Probleme nach wipes lösen",
			[19]		= " ",
			[20]		= "Warsong Gulch InfoFrame hinzugefügt",
			[21]		= "Four Horseman mod hinzugefügt",
			[22]		= "Thaddius phase 1 wird nun unterstützt (Kick und Power Surge)",
			[23]		= "Azuregos mod hinzugefügt (beta)",
			[24]		= "Sapphiron mod hinzugefügt (beta)",
			[25]		= "Kel'Thuzad mod hinzugefügt (beta)",
			[26]		= "Geddon Inferno Warnung hinzugefügt",
			[27]		= "Loatheb Spore Spawn Timer hinzugefügt",
			[28]		= "Käfer Explosions Warnung zum Twin Emperor Mod hinzugefügt",
			[29]		= "Statistik Tool für Flickwerk Kämpfe hinzugefügt (Hasserfüllte Stöße: x Treffer: y Verfehlt: z Ausgewichen: etc...",
			[30]		= "Option zum Entfernen von einzelnen Heilern aus der Loatheb Heiler Rotation hinzugefügt, einfach die ID auf 0 setzen um einen Heiler zu löschen. Um ihn wieder in die Liste aufzunehmen /loa undelete verwenden",
			[31]		= "OnStop Handler zu den Boss Mods hinzugefügt, diese werden aufgerufen, wenn das AddOn per Slash Command /mobname stop oder über den Button \"AddOn stoppen\" angehalten wird",
			[32]		= "Funktion LVBM.SendHiddenWhisper(msg, target) hinzugefügt, siehe API Dokumentation",
			[33]		= "Option zum Ansagen von Timern hinzugefügt, Shift + Linksklick auf die Bar um den Timer in den Raid bzw. Battleground Chat zu posten. Falls die Editbox des Chatframes gerade geöffnet ist, wird der Text dort eingefügt",
			[34]		= "Kampf Erkennungs System hinzugefügt, dieses System erlaubt einige Kampfbezogene Features wie z.B. das automatische beantworten von Whispers während man gerade gegen einen Boss kämpft. Außerdem wird nun immer im Chat angezeigt, wie lange der Kampf gedauert hat und einige andere kleine Spielereien :)",
			[35]		= "\"Automatisches Beantworten von Whispers\" Funktion hinzugefügt (Nur aktiviert während Kämpfen gegen Bosse und für Spieler die nicht in der Raid Gruppe sind)",
			[36]		= "OnCombatStart und OnCombatEnd Handler hinzugefügt. Da die Kampferkennung synchronisiert wird, erlauben diese Handler genauere Timer für einige Fähigkeiten",
			[37]		= "Funktion LVBM.StartColoredStatusBarTimer() zum Starten von Bars mit einer bestimmten Farbe hinzugefügt, diese Farbe überschreibt die vom Benutzer eingestellte, siehe API Dokumentation für Details",
			[38]		= "mehr Designs für die Bars hinzugefügt, siehe Optionen Menü und Screenshots",
			[39]		= " ",
			[40]		= " ",
		},
	},
}

StaticPopupDialogs["COPY_LVBM_URL"] = {
	text = LVBM_COPY_PASTE_NOW,
	button1 = LVBM_CLOSE,
	hasEditBox = 1,	
	button2 = "",
	
	OnShow = function()
		getglobal(this:GetName().."EditBox"):SetText("http://www.curse-gaming.com/de/wow/addons-4455-1-la-vendetta-boss-mods-naxxramas-ahnqiraj-blackwing-lair-molten-core-and-aq20zg.html");
		getglobal(this:GetName().."EditBox"):SetFocus();
		getglobal(this:GetName().."EditBox"):HighlightText();
		getglobal(this:GetName().."Button2"):Hide();
		getglobal(this:GetName().."Button1"):ClearAllPoints();
		getglobal(this:GetName().."Button1"):SetPoint("TOP", getglobal(this:GetName().."EditBox"), "BOTTOM", 0, -8);		
	end,
	OnHide = function()
		if ( ChatFrameEditBox:IsVisible() ) then
			ChatFrameEditBox:SetFocus();
		end
		getglobal(this:GetName().."EditBox"):SetText("");
		getglobal(this:GetName().."Button2"):Show();
	end,
	EditBoxOnEnterPressed = function()
		this:GetParent():Hide();
	end,
	EditBoxOnEscapePressed = function()
		this:GetParent():Hide();
	end,
	timeout = 0,
	exclusive = 1,
	whileDead = 1,
	hideOnEscape = 1
};
